#!/usr/bin/env bash

CONFIG="${UMBREL_ROOT}/app-data/stacks-blockchain/data/config/Config.toml"

set -e

     sed -i  -e "s@APP_BITCOIN_NODE_IP@$APP_BITCOIN_NODE_IP@" \
             -e "s@APP_BITCOIN_RPC_USER@$APP_BITCOIN_RPC_USER@" \
             -e "s@APP_BITCOIN_RPC_PASS@$APP_BITCOIN_RPC_PASS@" \
             -e "s@APP_BITCOIN_RPC_PORT@$APP_BITCOIN_RPC_PORT@" \
             -e "s@APP_STACKS_CORE_RPC_PORT@$APP_STACKS_CORE_RPC_PORT@" \
             -e "s@APP_STACKS_CORE_P2P_PORT@$APP_STACKS_CORE_P2P_PORT@" \
             -e "s@APP_STACKS_API_IP@$APP_STACKS_API_IP@" \
             -e "s@APP_STACKS_CORE_EVENT_PORT@$APP_STACKS_CORE_EVENT_PORT@" \
             -e "s@APP_BITCOIN_P2P_PORT@$APP_BITCOIN_P2P_PORT@" "$CONFIG"