version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_LNSWAP_APP_IP
      APP_PORT: $APP_LNSWAP_APP_PORT

  api:
    image: pseudozach/lnstxbridge-client:1.1.2
    restart: on-failure
    stop_grace_period: 1m
    #user: 1000:1000
    init: true
    ports:
      - $APP_LNSWAP_API_PORT:$APP_LNSWAP_API_PORT
    volumes:
      - ${APP_DATA_DIR}/data:/root/.lnstx-client/
      - ${APP_LIGHTNING_NODE_DATA_DIR}/data:/lnd:ro
    environment:
      BITCOIN_IP: $APP_BITCOIN_IP
      BITCOIN_RPC_PORT: $APP_BITCOIN_NODE_IP
      BITCOIN_RPC_USER: $APP_BITCOIN_RPC_USER
      BITCOIN_RPC_PASS: $APP_BITCOIN_RPC_PASS
      BITCOIN_NETWORK: ${BITCOIN_NETWORK:-mainnet}
      BITCOIN_ZMQ_RAWTX_PORT: $APP_BITCOIN_ZMQ_RAWTX_PORT
      BITCOIN_ZMQ_RAWBLOCK_PORT: $APP_BITCOIN_ZMQ_RAWBLOCK_PORT
      BITCOIN_ZMQ_HASHBLOCK_PORT: $APP_BITCOIN_ZMQ_HASHBLOCK_PORT
      LND_IP: $APP_LIGHTNING_IP
      LND_GRPC_PORT: $APP_LIGHTNING_NODE_GRPC_PORT
      APP_PASSWORD: "moneyprintergobrrr"
      APP_HIDDEN_SERVICE: ${APP_HIDDEN_SERVICE}
      APP_PORT: $APP_LNSWAP_API_PORT
    networks:
      default:
        ipv4_address: $APP_LNSWAP_API_IP

  dashboard:
    image: ceramicwhite/lnstxbridge-dashboard:1.1.2@sha256:3c6ac076fe77354892ababff5f09456dc78b7c2bed50545977d42137a88155ad
    restart: on-failure
    stop_grace_period: 1m
    #user: 1000:1000
    init: true
    environment:
      NEXT_PUBLIC_BACKEND_URL: "$APP_LNSWAP_API_IP:$APP_LNSWAP_API_PORT"
      PORT: $APP_LNSWAP_APP_PORT
    ports:
      - $APP_LNSWAP_APP_PORT:$APP_LNSWAP_APP_PORT
    depends_on:
      - api
    networks:
      default:
        ipv4_address: $APP_LNSWAP_APP_IP