
version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_STACKS_EXPLORER_IP
      APP_PORT: 3000

  stacks-explorer:
    image: ceramicwhite/stacks-explorer:latest-umbrel
    init: true
    restart: on-failure
    user: "1000:1000"
    stop_grace_period: 1m
    # Hiro Devs scuffed Next env vars so they are hardcoded into docker image on hub for now
    #environment:
      #NEXT_PUBLIC_MAINNET_API_SERVER: http://${APP_STACKS_API_IP}:${APP_STACKS_API_PORT}
      #NEXT_PUBLIC_TESTNET_API_SERVER: http://${APP_STACKS_API_IP}:${APP_STACKS_API_PORT}
      #NEXT_PUBLIC_LEGACY_EXPLORER_API_SERVER: https://explorer-api.legacy.blockstack.org
      #NEXT_PUBLIC_DEPLOYMENT_URL: ${DEVICE_HOSTNAME:-umbrel}.local:4009
      #NEXT_PUBLIC_MAINNET_ENABLED: "true"
      #NEXT_PUBLIC_DEFAULT_POLLING_INTERVAL: "10000"
      #NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      default:
        ipv4_address: $APP_STACKS_BLOCKCHAIN_IP
