version: "3.7"
# In the future want to add a dashboard page with gotty showing node stats for now just expose the api without auth
services:
  app_proxy:
    environment:
      APP_HOST: $APP_STACKS_API_IP
      APP_PORT: 3999
      PROXY_AUTH_WHITELIST: "/api/*"

  stacks-blockchain:
    image: ceramicwhite/stacks-blockchain:latest
    # Waiting for wileyj to post an image running as non-root
    #user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 10m
    command:
      [
        "/bin/stacks-node",
        "start",
        "--config",
        "/src/stacks-blockchain/Config.toml",
      ]
    ports:
      - $APP_STACKS_CORE_RPC_PORT:$APP_STACKS_CORE_RPC_PORT
      - $APP_STACKS_CORE_P2P_PORT:$APP_STACKS_CORE_P2P_PORT
    volumes:
      - ${APP_DATA_DIR}/data/stacks-blockchain:/root/stacks-blockchain/data
      - ${APP_DATA_DIR}/data/config:/src/stacks-blockchain
    networks:
      default:
        ipv4_address: $APP_STACKS_BLOCKCHAIN_IP

  stacks-blockchain-api:
    image: ceramicwhite/stacks-blockchain-api:latest
    init: true
    restart: on-failure
    stop_grace_period: 5m
    #user: "1000:1000"
    environment:
      NODE_ENV: production
      PG_HOST: postgres
      PG_PORT: $APP_STACKS_DB_PORT
      PG_USER: "umbrel"
      PG_PASSWORD: "moneyprintergobrrr"
      PG_DATABASE: postgres
      STACKS_CHAIN_ID: 0x00000001
      V2_POX_MIN_AMOUNT_USTX: 90000000260
      STACKS_CORE_EVENT_PORT: $APP_STACKS_CORE_EVENT_PORT
      STACKS_CORE_EVENT_HOST: 0.0.0.0
      STACKS_BLOCKCHAIN_API_PORT: $APP_STACKS_API_PORT
      STACKS_BLOCKCHAIN_API_HOST: 0.0.0.0
      STACKS_BLOCKCHAIN_API_DB: pg
      STACKS_CORE_RPC_HOST: stacks-blockchain
      STACKS_CORE_RPC_PORT: $APP_STACKS_CORE_RPC_PORT
      STACKS_API_ENABLE_FT_METADATA: 1
      STACKS_API_ENABLE_NFT_METADATA: 1
      BNS_IMPORT_DIR: /bns-data
      STACKS_EXPORT_EVENTS_FILE: /tmp/event-replay/stacks-node-events.tsv
    command: ["npm", "run", "start"]
    volumes:
      - ${APP_DATA_DIR}/data/bns-data:/bns-data
      - ${APP_DATA_DIR}/data/event-replay:/tmp/event-replay
    ports:
      - $APP_STACKS_CORE_EVENT_PORT:$APP_STACKS_CORE_EVENT_PORT
      - $APP_STACKS_API_PORT:$APP_STACKS_API_PORT
    networks:
      default:
        ipv4_address: $APP_STACKS_API_IP
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    restart: on-failure
    stop_grace_period: 5m
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: umbrel
      POSTGRES_PASSWORD: moneyprintergobrrr
      POSTGRES_DB: pg
      POSTGRES_PORT: $APP_STACKS_DB_PORT
    networks:
      default:
        ipv4_address: $APP_STACKS_DB_IP